"""Init1

Revision ID: 1a0f1740b06d
Revises: 4dfa129555f5
Create Date: 2024-01-11 19:31:15.019303

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1a0f1740b06d'
down_revision: Union[str, None] = '4dfa129555f5'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    
    op.create_table('groups',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(length=150))
    )

    op.create_table('teachers',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(length=150))
    )

    op.create_table('students',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(length=150)),
    sa.Column('group_id', sa.Integer()),
    sa.ForeignKeyConstraint(['group_id'], ['groups.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('disciplines',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('name', sa.String(length=150)),
    sa.Column('teacher_id', sa.Integer()),
    sa.ForeignKeyConstraint(['teacher_id'], ['teachers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )

    op.create_table('grades',
    sa.Column('id', sa.Integer(), primary_key=True),
    sa.Column('grade',  sa.Integer() ),
    sa.Column('discipline_id', sa.Integer()),
    sa.Column('student_id', sa.Integer()),
    sa.ForeignKeyConstraint(['discipline_id'], ['disciplines.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['student_id'], ['students.id'], ondelete='CASCADE'),
    # sa.Column( "date_off", sa.DateTime() )
    sa.PrimaryKeyConstraint('id')
    )



def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('disciplines')
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('groups')
    
