"""Init0

Revision ID: 4dfa129555f5
Revises: 
Create Date: 2024-01-11 18:52:02.150545

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4dfa129555f5'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    ...
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('grades')
    op.drop_table('disciplines')
    op.drop_table('students')
    op.drop_table('teachers')
    op.drop_table('groups')
