"""fix relationship

Revision ID: a82bc468097d
Revises: ecff53664819
Create Date: 2024-01-13 12:33:49.677816

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a82bc468097d'
down_revision: Union[str, None] = 'ecff53664819'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('disciplines_teacher_id_fkey', 'disciplines', type_='foreignkey')
    op.create_foreign_key(None, 'disciplines', 'teachers', ['teacher_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('grades_student_id_fkey', 'grades', type_='foreignkey')
    op.drop_constraint('grades_discipline_id_fkey', 'grades', type_='foreignkey')
    op.create_foreign_key(None, 'grades', 'students', ['student_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'grades', 'disciplines', ['discipline_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('groups_name_key', 'groups', type_='unique')
    op.drop_constraint('students_group_id_fkey', 'students', type_='foreignkey')
    op.create_foreign_key(None, 'students', 'groups', ['group_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'students', type_='foreignkey')
    op.create_foreign_key('students_group_id_fkey', 'students', 'groups', ['group_id'], ['id'])
    op.create_unique_constraint('groups_name_key', 'groups', ['name'])
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.drop_constraint(None, 'grades', type_='foreignkey')
    op.create_foreign_key('grades_discipline_id_fkey', 'grades', 'disciplines', ['discipline_id'], ['id'])
    op.create_foreign_key('grades_student_id_fkey', 'grades', 'students', ['student_id'], ['id'])
    op.drop_constraint(None, 'disciplines', type_='foreignkey')
    op.create_foreign_key('disciplines_teacher_id_fkey', 'disciplines', 'teachers', ['teacher_id'], ['id'])
    # ### end Alembic commands ###
